# Basic Neural Network Building Blocks

This notebook showcases four fundamental operations used in deep learning:

1. **ReLU** activation
2. **Max Pooling**
3. **Linear (fully connected) layer**
4. **Reshape**

We use PyTorch for all examples.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(0)

## 1. ReLU

ReLU (Rectified Linear Unit) replaces every negative value with zero and keeps positive values unchanged: `relu(x) = max(0, x)`.

In [2]:
x = torch.tensor([-2.0, -0.5, 0.0, 1.0, 3.0])
relu = nn.ReLU()

print("input: ", x)
print("relu:  ", relu(x))

input:  tensor([-2.0000, -0.5000,  0.0000,  1.0000,  3.0000])
relu:   tensor([0., 0., 0., 1., 3.])


## 2. Max Pooling

Max pooling slides a window over the input and keeps only the maximum value in each window. It reduces spatial size while keeping the strongest activations.

Here we apply a 2x2 max pool to a single 4x4 image (shape `[batch, channels, height, width]`).

In [3]:
img = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
pool = nn.MaxPool2d(kernel_size=2, stride=2)

print("input (4x4):")
print(img[0, 0])
print("\nafter 2x2 max pool (2x2):")
print(pool(img)[0, 0])

input (4x4):
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

after 2x2 max pool (2x2):
tensor([[ 5.,  7.],
        [13., 15.]])


## 3. Linear Layer

A linear (fully connected) layer computes `y = x @ W.T + b`. It maps an input vector of size `in_features` to an output vector of size `out_features`.

In [4]:
linear = nn.Linear(in_features=4, out_features=2)

vec = torch.tensor([[1.0, 2.0, 3.0, 4.0]])  # shape [batch=1, 4]
out = linear(vec)

print("weight shape:", linear.weight.shape)
print("bias shape:  ", linear.bias.shape)
print("input shape: ", vec.shape)
print("output:      ", out)
print("output shape:", out.shape)

weight shape: torch.Size([2, 4])
bias shape:   torch.Size([2])
input shape:  torch.Size([1, 4])
output:       tensor([[-2.2181,  1.7639]], grad_fn=<AddmmBackward0>)
output shape: torch.Size([1, 2])


## 4. Reshape

Reshape changes the shape of a tensor without changing its data. This is commonly used to flatten feature maps before a linear layer. Using `-1` lets PyTorch infer that dimension automatically.

In [5]:
feat = torch.arange(12, dtype=torch.float32).reshape(1, 3, 2, 2)
print("original shape:", feat.shape)

flat = feat.reshape(1, -1)
print("flattened shape:", flat.shape)
print(flat)

original shape: torch.Size([1, 3, 2, 2])
flattened shape: torch.Size([1, 12])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])


## Putting It Together

A typical convolutional block flows like: max pool -> reshape (flatten) -> linear -> ReLU.

In [6]:
x = torch.randn(1, 1, 4, 4)

x = nn.MaxPool2d(2, 2)(x)   # -> [1, 1, 2, 2]
x = x.reshape(1, -1)         # -> [1, 4]
x = nn.Linear(4, 3)(x)       # -> [1, 3]
x = F.relu(x)                # -> [1, 3]

print("final output:", x)
print("final shape: ", x.shape)

final output: tensor([[0., 0., 0.]], grad_fn=<ReluBackward0>)
final shape:  torch.Size([1, 3])
